package com.prodash.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * Represents a legislative proposal as stored in our database.
 * The @Document annotation marks this class as a MongoDB document.
 */
@Data
@NoArgsConstructor
@Document(collection = "proposals")
public class Proposal {

    @Id
    private String id; // MongoDB's default ID

    private Long originalId; // The ID from the Camara API
    private String siglaTipo;
    private int numero;
    private int ano;
    private String ementa; // Original summary text

    private String summaryLLM; // The summary generated by the LLM
    private String categoryLLM; // The category assigned by the LLM

    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
